export { default as HomeScreen } from './Home'
export { default as AdminPacientes } from './AdminPacientes'
export { default as AdminClientes } from './AdminClientes'
export { default as ReporteVentasResumido } from './ReporteVentasResumido'
export { default as ReporteVentasDetallado } from './ReporteVentasDetallado'
